swagger: "2.0"
info:
  description: "接口文档"
  version: "v1"
  title: "接口文档"
  termsOfService: ""
  contact:
    email: ""
  license:
    name: ""
    url: ""
host: "192.168.20.7:8000"
basePath: "/api"

schemes:
- "https"
- "http"

paths:

  /login:
    post:
      tags:
        - 账号管理
      summary: 登录
      description: 登录
      parameters:
        - name: body
          in: body
          required: true
          description: 用户名
          schema:
            $ref: '#/definitions/LoginPayloadData'
      responses:
        200:
          description: 成功。
          schema:
            $ref: '#/definitions/LoginResponse'

definitions:
  Success:
    type: object
    properties:
      code:
        type: string
        description: 状态码 200 表示成功
      msg:
        type: string
        description: 状态描述
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
        default: 500
        description: 错误代码
      msg:
        type: string
        description: 错误描述

  LoginPayloadData:
    properties:
      username:
        type: string
        descripton: 用户名
      password:
        type: string
        description: 密码
  LoginResponse:
    type: object
    properties:
      code:
        type: integer
        default: 200
        description: 状态码 200 表示成功
      msg:
        type: string
        default: 返回成功
        description: 状态描述
      data:
        description: 登录返回结果
        $ref: '#/definitions/LoginData'
  LoginData:
    properties:
      id:
        type: integer
        description: 用户id
      token:
        type: string
        description: 认证令牌
